### ISSUE TITLE
Add Link Aula 4

### ISSUE THREAD

**Issue by ebraimcarvalho** [rodolfoghi/curso-labhacker-analise-dados-com-python#2]
Verifiquei que no Readme não consta o link da aula 4, penso que saiu depois da criação do repo. Então resolvi mandar por aqui, beleza?

https://www.youtube.com/watch?v=hyDvL_CzbX4&t=9s

**Comment by rodolfoghi** [comment]
Ainda não fiz essa aula, mas adicionei o link no readme. Obrigado @ebraimcarvalho.
